In [1]:
[x for x in ["bla","oh","jaja","i","ah"] if len(x)==2]

['oh', 'ah']

In [2]:
esigualados = lambda x: len(x)==2
list(filter(esigualados, ["bla", "oh", "jaja", "i", "ah"]))

['oh', 'ah']

In [3]:
"""""""

Osea que

list(filter(lambda x: len(x)==2, ["bla", "oh", "jaja", "i", "ah"]))

Da el mismo resultado que hacer el comprehension:
[x for x in ["bla","oh","jaja","i","ah"] if len(x)==2]


Osea

["oh","ah"]

SyntaxError: EOL while scanning string literal (<ipython-input-3-4697adf572f5>, line 1)

In [4]:
tiene_dos_letras= lambda x: len(x) ==2

lista=["kk", "avion", "hola", "si"]

filtrada = list(filter(tiene_dos_letras, lista))

print(filtrada) # esto imprime ["kk", "si"]

['kk', 'si']


In [5]:
es_azul = lambda x: x=="azul"


lista="rojo,verde,azul,amarillo,azul".split(",")

filtrada=list(filter(es_azul, lista))
print(filtrada) # esto imprime [“azul”, “azul]

['azul', 'azul']


In [6]:
def _f_protected(): 
    x_es_mayor_que_cinco = lambda x : x>5
    l1=[elem for elem in range(16)]
    y= list(filter(x_es_mayor_que_cinco,l1))
    return (y)
    print (y)

_f_protected()

[6, 7, 8, 9, 10, 11, 12, 13, 14, 15]

json inside column dataframe python 

la primera opcion en google 

In [7]:
from functools import wraps
​
def pepe_el_decorador(*args, **kwargs):
    def alter_ego_de_pepe(cualquier_funcion_que_pepe_decore):
        @wraps(cualquier_funcion_que_pepe_decore)
        def wrapper(*a, **k):
            if args:
                print("args:",args)
            if kwargs:
                print("kwargs:",kwargs)
            if a:
                print("a:",a)
            if k:
                print("k:",k)
            return ("esto es lo que devuelve 'wrapper':",cualquier_funcion_que_pepe_decore(*a,**k))
        print(wrapper, "\nlo devuelve la función alter_ego_de_pepe")
        return wrapper
    return alter_ego_de_pepe
​
​
@pepe_el_decorador(808080, quiwars="este es el valor de kwargs del decorador")
def funcion_decorada_por_pepe(ar, kw):
    print("este es el parámetro 'ar' de 'funcion_decorada_por_pepe:", ar)
    print("este es el parámetro 'kw':",kw)
    return "Esto es lo que devuelve la función decorada"
​
funcion_decorada_por_pepe("en wrapper soy '*a'", kw = "en wrapper soy '**k'")

SyntaxError: invalid character in identifier (<ipython-input-7-a0191b048037>, line 2)

In [8]:
jason.normalize 



NameError: name 'jason' is not defined

In [9]:
forma de hacer version principiante
def concatena_dataframes1(df1, df2): 
    df_list = [df1, df2]
    concatenados = pd.concat(df_list, axis=0)
    return concatenados

forma d ehacerlo version pro

def concatena_dataframes2(df1, df2): 
    return pd.concat([df1, df2], axis=0)

SyntaxError: invalid syntax (<ipython-input-9-8f6d73fc38fd>, line 1)

In [10]:
def factorial(n):
    if n ==1:
        return n
    else:
        return n * factorial(n-1)

#es una funcion recursiva que me calcula directamente el factorial de un numero def factorial(n):
   

In [11]:
#ejercicio covid
import pandas as pd
#entendiendo lo que estoy haciendo en un ejemplo imaginario con datos mas simples para aclararme 
lista=[
    {"date":"blabla", "metadata":{"x":"y", "z":{"v":[]}}, "title":"A"},
    {"date":"bleble", "metadata":{"x":"y", "z":{"v":[]}}, "title":"B"}
]
# Leer de forma directa:
pd.DataFrame(lista)

date                    metadata title
0  blabla  {'x': 'y', 'z': {'v': []}}     A
1  bleble  {'x': 'y', 'z': {'v': []}}     B

In [12]:
#ejercicio covid 
# Leer la lista cuando está anidada dentro de diccionarios con un ejemplo más simple para aclararme 

item={
    "data":{
        "post": [
                  {"date":"blabla", "metadata":{"x":"y", "z":{"v":[]}}, "title":"A"},
                  {"date":"bleble", "metadata":{"x":"y", "z":{"v":[]}}, "title":"B"}
                ]
    }
}


df_x =pd.DataFrame(item)

post = df_x.data.post
pd.DataFrame(post)

date                    metadata title
0  blabla  {'x': 'y', 'z': {'v': []}}     A
1  bleble  {'x': 'y', 'z': {'v': []}}     B

In [13]:
#ejercicio nba18
#entendiendo lo que estoy haciendo con un ejemplo con valores más sencillos 
df1 = pd.DataFrame([{"a":1},{"a":2}])
df2 = pd.DataFrame([{"a":3},{"a":4}])
pd.concat([df1,df2], axis=0)#entendiendo lo que estoy haciendo con un ejemplo con valores más sencillos 
df1 = pd.DataFrame([{"a":1},{"a":2}])
df2 = pd.DataFrame([{"a":3},{"a":4}])
pd.concat([df1,df2], axis=0)

a
0  1
1  2
0  3
1  4

In [14]:
In [3]: np.<TAB>


SyntaxError: invalid syntax (<ipython-input-14-cafe7d82c7d0>, line 1)

In [15]:
In [4]: np?

Object `np` not found.


In [16]:
import numpy as np
np.random.seed(0)

In [17]:
x1 = np.zeros(6)  # One-dimensional array
x2 = np.ones((3, 4)) # Two-dimensional array
x3 = np.ones((3, 4, 5))  # Three-dimensional array

In [18]:
x1

array([0., 0., 0., 0., 0., 0.])

In [19]:
x2 = np.ones((3, 4)) #3 son las filas, y 4 son las columnas (3 filas, 4 columnas). este array es bidimensional. 
x2 #

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [20]:
x3 = np.ones((3, 4, 5))  # Three-dimensional array. 3 arrays, 4 filas, 5 columnas 

In [21]:
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

itemsize: 8 bytes
nbytes: 480 bytes


In [22]:
#Si está familiarizado con la indexación de lista estándar de Python, la indexación en NumPy le resultará bastante familiar. En una matriz unidimensional, se puede acceder al valor i-ésimo (contando desde cero) especificando el índice deseado entre corchetes, al igual que con las listas de Python:

In [23]:
x1

array([0., 0., 0., 0., 0., 0.])

In [24]:
x1[0]

0.0

In [25]:
x1[4]

0.0

In [26]:
#Values can also be modified using any of the above index notation:
#ha sustituido el valor del 0.0 (era 1.) por un 12
x2[0, 0] = 12
x2

array([[12.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [27]:
#Tenga en cuenta que, a diferencia de las listas de Python, las matrices NumPy tienen un tipo fijo. Esto significa, por ejemplo, que si intenta insertar un valor de punto flotante en una matriz entera, el valor se truncará silenciosamente. ¡No se deje sorprender por este comportamiento!

In [28]:
x1

array([0., 0., 0., 0., 0., 0.])

In [29]:
x1[0] = 3.14159  # this will be truncated! #preguntar a Clara 
x1

array([3.14159, 0.     , 0.     , 0.     , 0.     , 0.     ])

In [30]:
#Del mismo modo que podemos usar corchetes para acceder a elementos de matriz individuales, también podemos usarlos para acceder a submatrices con la notación de corte, marcada con el carácter de dos puntos (:). La sintaxis de segmentación NumPy sigue la de la lista estándar de Python; para acceder a un segmento de una matriz x, use esto: x [inicio: detener: paso]
#Si alguno de estos no está especificado, los valores predeterminados son inicio = 0, parada = tamaño de dimensión, paso = 1. Echaremos un vistazo al acceso a sub-matrices en una dimensión y en múltiples dimensiones.

In [31]:
x = np.arange(10)
print (np.arange(10))

[0 1 2 3 4 5 6 7 8 9]


In [32]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
x[:5]  # first five elements

array([0, 1, 2, 3, 4])

In [34]:
x[4:7]

array([4, 5, 6])

In [35]:
x[::2]  # every other element. Aqui saca los pares

array([0, 2, 4, 6, 8])

In [36]:
x[1::2]  # every other element, starting at index 1. saca los impares 

array([1, 3, 5, 7, 9])

In [37]:
x[::-1]  # all elements, reversed

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [38]:
x[5::-2]  # reversed every other from index 5

array([5, 3, 1])

In [39]:
#SLICING LA PARTE DE LA IZQUIERDA SON FILAS Y LA DE LA DERECHA SON COLUMNAS 

In [40]:
x2

array([[12.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [41]:
x2[:2, :3]  # two rows, three columns LA PARTE DE LA IZQUIERDA SON FILAS Y LA DE LA DERECHA SON COLUMNAS 

array([[12.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [42]:
x2[:3, ::2]  # all rows (filas), every other column

array([[12.,  1.],
       [ 1.,  1.],
       [ 1.,  1.]])

In [43]:
x2

array([[12.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [44]:
x2

array([[12.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [45]:
x2[:3, ::1]  # all rows, every other column ME QUEDA POR ENTENDER ESTO 

array([[12.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [46]:
name="Jaime"
blabla="loquesea"
print("I am "+name+ ", and I like"+blabla+"at night")
print(f"I am {name} and I like {blabla} at night")

I am Jaime, and I likeloqueseaat night
I am Jaime and I like loquesea at night


In [47]:
def numeritos(n):
    return list(range(n))

a=numeritos(5)
a


[0, 1, 2, 3, 4]

In [48]:
def numerotes(n):
    return ["x"] * n

numerotes(3)

['x', 'x', 'x']

In [49]:
def funcion_chunga(f, numero): #lo que está entre parentesis son variables 
    l = f(n=numero)
    l.append("kk")
    return l

x=funcion_chunga(f=numeritos, numero=1) #necesario para darle sentido a la funcion
x

[0, 'kk']

In [50]:
print(funcion_chunga(numeritos, numero=5))
print(funcion_chunga(numerotes, numero=1))


[0, 1, 2, 3, 4, 'kk']
['x', 'kk']


In [51]:


def funcion(f, texto):
    f(texto)

a=funcion(print, "hola mundo")
print(a)

hola mundo
None


In [52]:
f1 = list
f2 = print


In [53]:
f1("Hola mundo")

['H', 'o', 'l', 'a', ' ', 'm', 'u', 'n', 'd', 'o']

In [54]:
f2("hola mundo")

hola mundo


In [55]:
def sumar_uno(a):
    return a+1

g= sumar_uno

g(8)

9

In [56]:
sumar_uno

<function __main__.sumar_uno(a)>

In [57]:


n = 1

def cambiar_n():
    global n
    n=n+1
    return "jaime"

print(n) #devuelve la variable 
print(cambiar_n()) #imprime jaime porque se lo estamos pidiendo con el return, pero si no tuvieramos el return, imprimiría solo None. 
print(n) #imprime 2 porque la función ha operado y ha cambiado el valor de n 

1
jaime
2


In [58]:
z=cambiar_n()
z


'jaime'

In [59]:
z

'jaime'

In [60]:
 
n = 1
def cambiar_n():
    global n
    n=n+1
    return "jaime"

x = cambiar_n() 
print(n) #imprime 2 porque ya ha pasado por la funcion
print(n) #lo mismo

print(x) #imprime jaime porque le estamos pidiedo que imprima lo que devuelve la funcion cambiar_n (que es jaime)
#atencion, los prints que hacemos muetsran la ejecución según se ha ido haciendo en vertical hacia abajo 


2
2
jaime


In [61]:
del x